# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     fongandrew/hydeout

# Setup
title:            Class website
tagline:          
description:      Reproducible research on child and youth development
